
// Auto-generated Machine Learning Model
// Predicts Health Recommendation based on: [Age, BMI, SleepHours, ExerciseHours, StressLevel]

const CLASS_MAPPING = {
  "0": "General Balanced Health Routine",
  "1": "High Performance & Nutrition Maintenance",
  "2": "Senior Wellness & Joint Care Plan",
  "3": "Stress Reduction & Sleep Therapy Plan",
  "4": "Weight Management & Cardio Plan"
};

function score(input) {
    var var0;
    if (input[1] <= 29.994903564453125) {
        if (input[4] <= 6.5) {
            if (input[2] <= 6.005974292755127) {
                if (input[3] <= 2.472899913787842) {
                    if (input[1] <= 25.035078048706055) {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    } else {
                        var0 = [0.0, 0.0, 0.0, 0.0, 1.0];
                    }
                } else {
                    if (input[3] <= 3.0346611738204956) {
                        var0 = [0.0, 0.0, 0.0, 0.8571428571428571, 0.14285714285714285];
                    } else {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    }
                }
            } else {
                if (input[0] <= 59.5) {
                    if (input[1] <= 24.99467945098877) {
                        var0 = [0.5517241379310345, 0.4482758620689655, 0.0, 0.0, 0.0];
                    } else {
                        var0 = [0.7716535433070866, 0.0, 0.0, 0.0, 0.2283464566929134];
                    }
                } else {
                    if (input[3] <= 2.3707377910614014) {
                        var0 = [0.0, 0.0, 0.5517241379310345, 0.0, 0.4482758620689655];
                    } else {
                        var0 = [0.0, 0.0, 0.9841269841269841, 0.0, 0.015873015873015872];
                    }
                }
            }
        } else {
            if (input[3] <= 2.936476945877075) {
                if (input[1] <= 24.82292366027832) {
                    var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                } else {
                    var0 = [0.0, 0.0, 0.0, 0.0, 1.0];
                }
            } else {
                var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
            }
        }
    } else {
        var0 = [0.0, 0.0, 0.0, 0.0, 1.0];
    }
    return var0;
}


export function predictRecommendation(age, bmi, sleepHours, exerciseHours, stressLevel) {
  const input = [age, bmi, sleepHours, exerciseHours, stressLevel];
  
  // score is generated by m2cgen
  const outputScores = score(input);
  
  // The output is an array of probabilities/scores for each class
  // Find the index of the max score
  let maxIdx = 0;
  let maxScore = outputScores[0];
  for (let i = 1; i < outputScores.length; i++) {
    if (outputScores[i] > maxScore) {
      maxScore = outputScores[i];
      maxIdx = i;
    }
  }
  
  return CLASS_MAPPING[maxIdx];
}
