
// Auto-generated Machine Learning Model
// Predicts Health Recommendation based on: [Age, BMI, SleepHours, ExerciseHours, StressLevel]

const CLASS_MAPPING = {
  "0": "General Balanced Health Routine",
  "1": "High Performance & Nutrition Maintenance",
  "2": "Senior Wellness & Joint Care Plan",
  "3": "Stress Reduction & Sleep Therapy Plan",
  "4": "Weight Management & Cardio Plan"
};

function score(input) {
    var var0;
    if (input[0] <= 60.5) {
        if (input[1] <= 25.000761032104492) {
            if (input[3] <= 7.022377252578735) {
                if (input[4] <= 7.5) {
                    var0 = [1.0, 0.0, 0.0, 0.0, 0.0];
                } else {
                    if (input[2] <= 5.848442077636719) {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    } else {
                        var0 = [1.0, 0.0, 0.0, 0.0, 0.0];
                    }
                }
            } else {
                if (input[4] <= 7.5) {
                    var0 = [0.0, 1.0, 0.0, 0.0, 0.0];
                } else {
                    if (input[2] <= 6.042063236236572) {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    } else {
                        var0 = [0.0, 1.0, 0.0, 0.0, 0.0];
                    }
                }
            }
        } else {
            if (input[3] <= 2.983242154121399) {
                if (input[1] <= 30.043938636779785) {
                    if (input[4] <= 7.5) {
                        var0 = [1.0, 0.0, 0.0, 0.0, 0.0];
                    } else {
                        var0 = [0.5294117647058824, 0.0, 0.0, 0.47058823529411764, 0.0];
                    }
                } else {
                    var0 = [0.0, 0.0, 0.0, 0.0, 1.0];
                }
            } else {
                if (input[2] <= 5.948799133300781) {
                    if (input[4] <= 7.5) {
                        var0 = [1.0, 0.0, 0.0, 0.0, 0.0];
                    } else {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    }
                } else {
                    var0 = [1.0, 0.0, 0.0, 0.0, 0.0];
                }
            }
        }
    } else {
        if (input[1] <= 24.781051635742188) {
            if (input[3] <= 6.9899866580963135) {
                if (input[2] <= 5.970296859741211) {
                    if (input[4] <= 7.5) {
                        var0 = [0.0, 0.0, 1.0, 0.0, 0.0];
                    } else {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    }
                } else {
                    var0 = [0.0, 0.0, 1.0, 0.0, 0.0];
                }
            } else {
                if (input[4] <= 7.5) {
                    var0 = [0.0, 1.0, 0.0, 0.0, 0.0];
                } else {
                    if (input[2] <= 6.005626440048218) {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    } else {
                        var0 = [0.0, 1.0, 0.0, 0.0, 0.0];
                    }
                }
            }
        } else {
            if (input[3] <= 2.8778257369995117) {
                if (input[1] <= 30.068392753601074) {
                    if (input[4] <= 8.5) {
                        var0 = [0.0, 0.0, 0.9655172413793104, 0.034482758620689655, 0.0];
                    } else {
                        var0 = [0.0, 0.0, 0.5, 0.5, 0.0];
                    }
                } else {
                    var0 = [0.0, 0.0, 0.0, 0.0, 1.0];
                }
            } else {
                if (input[4] <= 7.5) {
                    var0 = [0.0, 0.0, 1.0, 0.0, 0.0];
                } else {
                    if (input[2] <= 6.045717477798462) {
                        var0 = [0.0, 0.0, 0.0, 1.0, 0.0];
                    } else {
                        var0 = [0.0, 0.0, 1.0, 0.0, 0.0];
                    }
                }
            }
        }
    }
    return var0;
}


export function predictRecommendation(age, bmi, sleepHours, exerciseHours, stressLevel) {
  const input = [age, bmi, sleepHours, exerciseHours, stressLevel];
  
  // score is generated by m2cgen
  const outputScores = score(input);
  
  // The output is an array of probabilities/scores for each class
  // Find the index of the max score
  let maxIdx = 0;
  let maxScore = outputScores[0];
  for (let i = 1; i < outputScores.length; i++) {
    if (outputScores[i] > maxScore) {
      maxScore = outputScores[i];
      maxIdx = i;
    }
  }
  
  return CLASS_MAPPING[maxIdx];
}
